version: '2'
services:
    jfcrm-app:
        image: jfcrm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jfcrm-mysql:3306/jfcrm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jfcrm-mysql:
        extends:
            file: mysql.yml
            service: jfcrm-mysql
